name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The (SemVer compliant) version of the release'
        required: true

jobs:
  release:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Checkout Repository'
      uses: 'actions/checkout@v2'
    - name: 'Make Some Changes'
      run: 'echo ${{ github.event.inputs.version }}'
    # - name: 'Push Documentation Changes And Tag'
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with:
    #     commit_message: 'Update documentation for release ${{ github.event.inputs.version }}'
    #     tagging_message: 'v${{ github.event.inputs.version }}'
